include ../config.mak

#SRCS =  ./source/core/matrix.cpp  \
#./source/objdetect/cascadedetect.cpp  \
#./source/objdetect/haar.cpp  \

SRCS =  $(wildcard ./source/imgproc/*.cpp)  
SRCS +=  $(wildcard ./source/core/*.cpp)  
SRCS +=  $(wildcard ./source/highgui/*.cpp)  



TARGET = Opencv
		
include ../target.mak
